# App Information
ios_app_id                                : 1617877213                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : android                                   # Enter Google Play Store URL.

app_icon                                  : assets/appicon.webp                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Stephan Lerner                                
your_link                                 : https://www.linkedin.com/in/stephan-lerner-301ba091/                     
your_city                                 : Hamburg                                
email_address                             : info@monee-app.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : Lausbert
youtube_username                          :

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.webp                    
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0
cover_overlay_start_position              : 0%
cover_overlay_end_transparency            : 0.5

body_background_color                     : "#ffffff"

link_color                                : "#3CBCB8"

banner_color                              : "#3CBCB8"
banner_transparency                       : 0.8

app_title_color                           : "#ffffff"
app_description_color                     : "#ffffff"

review_card_background_color              : "#f7f7f7"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#3CBCB8"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
  - vendor

include:
  - .well-known

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-multiple-languages-plugin

languages: ["en", "de", "fr"]

# Site URL
url: "https://monee-app.com"