#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1617877213                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Monee - Family Budget Book                # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : In-App-Purchases                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Monee puts you back in control of your finances.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Stephan Lerner                                
your_link                                 : https://www.linkedin.com/in/stephan-lerner-301ba091/                     
your_city                                 : Hamburg                                
email_address                             : stephanlerner@icloud.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : Lausbert3000
github_username                           : Lausbert
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Shared Household
    description                           : Invite others to your household and manage your finances together
    fontawesome_icon_name                 : users
    
  - title                                 : Recurring Transactions
    description                           : Create recurring costs that are automatically added to your transactions
    fontawesome_icon_name                 : sync

  - title                                 : Overview & Insights
    description                           : Get a good overview or deep insights where you think it is necessary
    fontawesome_icon_name                 : chart-line

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.3

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#87BDBB"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#87BDBB"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-multiple-languages-plugin